apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-microservice-logs
  namespace: statex-apps
  labels:
    app: logging-microservice
    managed-by: k8s-migration
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
