apiVersion: v1
kind: Service
metadata:
  name: logging-microservice
  namespace: statex-apps
  labels:
    app: logging-microservice
    managed-by: k8s-migration
spec:
  type: ClusterIP
  selector:
    app: logging-microservice
  ports:
    - protocol: TCP
      port: 3367
      targetPort: 3367
      name: http
